const ListaProductos = [
        {
            "ID": 1,
            "NombreLibro": "All Star Superman Deluxe Edition",
            "Autor": "Grant Morrison",
            "Editorial": "DC Comics",
            "ISBN": 1779513445,
            "AnnoPublicacion": 2022,
            "Idioma": "Inglés",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 28000,
            "Descripcion": "¡AVENTURAS DE SUPERMÁN! Locura al revés en el planeta Bizarro al revés.Una ciudad embotellada que demuestra que nunca podrás volver a casa.Un sol viviente empeñado en destruir a la humanidad.Un mundo sin el Hombre de Acero.Doce trabajos imposibles y meros momentos para salvar la Tierra.\nEl multipremiado ALL-STAR SUPERMAN es una historia eterna fiel al personaje más grande de la época dorada de los cómics.Sea testigo del ícono atemporal, el Hombre de Acero, en acción en esta colección de lujo llena de emoción y aclamación.",
            "ImagenDestacada": "https://m.media-amazon.com/images/I/81oiYDSaoVL._SL1500_.jpg",
            "Stock": "Disponible online",
            "GaleriaImg": ["https://m.media-amazon.com/images/I/81oiYDSaoVL._SL1500_.jpg","https://m.media-amazon.com/images/I/81UsnOXb5zL._AC_UF1000,1000_QL80_.jpg","https://i5.walmartimages.com/seo/All-Star-Superman-Paperback-9781401232054_4d5856f7-91ed-432a-a0ca-583e6ffa7e8b_1.d253c8f89f3879735cafccc1c1fa5ab6.jpeg"], 
            "TiempoEntrega": "4 días",            
            "OpcionesEntrega": "Envío postal",
            "Garantia": "24 horas",
            "Resenna": "./IMG/4_5_Estrellas.png"
        },
        {
            "ID": 2,
            "NombreLibro": "Batman The Long Halloween",
            "Autor": "Jehph Loeb",
            "Editorial": "DC Comics",
            "ISBN": 1401232590,
            "AnnoPublicacion": 2011,
            "Idioma": "Inglés",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 22800,
            "Descripcion": "Navidad.\nDía de San Patricio.\nPascua.\nA medida que se acumulan los días del calendario, también se acumulan los cuerpos esparcidos por las calles de Gotham City.\nUn asesino anda suelto, matando solo en días festivos.\n¿El único hombre que puede detener a este demonio? El caballero oscuro.\nEn un misterio que tiene lugar durante los primeros días de lucha contra el crimen de Batman, Batman: The Long Halloween es una de las mejores historias jamás contadas del Caballero Oscuro.\nTrabajando con el fiscal de distrito Harvey Dent y el teniente James Gordon, Batman compite contra el calendario mientras intenta descubrir quién es Holiday antes de reclamar a su próxima víctima cada mes.\nUn misterio que hace que el lector adivine continuamente la identidad del asesino, esta historia también se relaciona con los eventos que transforman a Harvey Méllate en el enemigo mortal de Batman, Two-Face.\nEl magnífico equipo creativo de Jeph Loeb y Tim Sale alcanza su cúspide en Batman: The Long Halloween.\nEsta edición incluye 13- serie de números, así como cuatro páginas adicionales de la historia recortadas de la serie original, que se presentan completamente coloreadas y restauradas en su lugar en la historia.\nTambién se incluyen bocetos y una introducción del director y escritor de The Dark Knight Rises, Christopher Nolan y David Goyer.",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9781401232597_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Disponible online o en tienda física",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9781401232597_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://upload.wikimedia.org/wikipedia/en/5/52/Batman_thelonghalloween.jpg","https://static.dc.com/sites/default/files/imce/2014/10-OCT/BM.Halloween_580_5445b72ba3a792.05974488.jpg"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Envío postal o recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "./IMG/5_Estrellas.png"
        },
        {
            "ID": 3,
            "NombreLibro": "Berserk Maximum Vol 01",
            "Autor": "Kentaro Miura",
            "Editorial": "PANINI MANGA",
            "ISBN": 9788411015035,
            "AnnoPublicacion": 2022,
            "Idioma": "Español",
            "Categorias": ["Ficción","Manga","Seinen"],
            "Precio": 16800,
            "Descripcion": "Edición de lujo de una de las más aclamadas series manga de todos los tiempos. Un viaje épico y salvaje a un reino de fantasía. Guts es un guerrero vestido de negro de los pies a la cabeza que porta una gigantesca espada más larga que su propia estatura y un robusto brazo ortopédico de hierro... Para lectores adultos.",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9788411015035_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Disponible online",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9788411015035_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema001y_0_1.jpg","https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/b/sbema001y_1_1.jpg"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Envío postal",
            "Garantia": "24 horas",
            "Resenna": "./IMG/4_5_Estrellas.png"
        },
        {
            "ID": 4,
            "NombreLibro": "Dragon Ball Super Vol 20",
            "Autor": "Akira Toriyama",
            "Editorial": "IVREA",
            "ISBN": 1974743608,
            "AnnoPublicacion": 2023,
            "Idioma": "Español",
            "Categorias": ["Ficción","Manga","Shonen"],
            "Precio": 7900,
            "Descripcion": "¡La aventura de Goku del manga clásico más vendido Dragon Ball continúa en esta nueva serie escrita por el propio Akira Toriyama!\nDesde que Goku se convirtió en el héroe más grande de la Tierra y reunió a los siete Dragon Balls para derrotar al malvado Boo, su vida en la Tierra se ha vuelto un poco aburrida. ¡Pero nuevas amenazas se ciernen sobre sus cabezas, y Goku y sus amigos tendrán que defender el planeta una vez más en esta continuación de la serie más vendida de Akira Toriyama, Dragon Ball!\nGoku y Vegeta están luchando por dominar sus respectivas ultra formas, que necesitarán para derrotar a Gas, ahora el guerrero más fuerte del universo. ¿Podrá Granolah volver a unirse a la batalla y ayudar a cambiar las cosas? Más tarde, de vuelta en casa, ¡un par de superhéroes están en los titulares! ¡Prepárate para una nueva historia ambientada en la Tierra!",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9781974743605_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Solo tienda física",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9781974743605_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://cdn11.bigcommerce.com/s-89ffd/images/stencil/1280x1280/products/147451/541184/9784088834702_1898da2044c82ec5dffa9060ced64c64__59879.1716431806.jpg?c=2?imbypass=on","https://www.libreriainternacional.com/media/catalog/product/9/7/9781974743605_2.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "./IMG/5_Estrellas.png"
        },
        {
            "ID": 5,
            "NombreLibro": "Jujutsu Kaisen Vol 14",
            "Autor": "Gege Akutani",
            "Editorial": "Norma Editorial",
            "ISBN": 9788411013017,
            "AnnoPublicacion": 2023,
            "Idioma": "Español",
            "Categorias": ["Ficción","Manga","Seinen"],
            "Precio": 8900,
            "Descripcion": "Mientras Sukuna, que tras haber obtenido la libertad de forma temporal se está comportando de un modo violento y cruel, ocasionando enormes daños en el barrio de Shibuya, Fushiguro recibe una herida mortal por un ataque sorpresa de un hechicero maldito y decide usar su último recurso. ¡Sukuna se ha dado cuenta de que Fushiguro ha empezado un “ritual de exorcismo” y…!",
            "ImagenDestacada": "https://m.media-amazon.com/images/I/81ZwggSh1zL._SY466_.jpg",
            "Stock": "Disponible online",
            "GaleriaImg": ["https://m.media-amazon.com/images/I/81ZwggSh1zL._SY466_.jpg","https://static.wikia.nocookie.net/jujutsu-kaisen/images/6/6b/Volume_14_Illustration.png/revision/latest?cb=20210607173940","https://static.wikia.nocookie.net/jujutsu-kaisen/images/2/2c/Chapter_116.png/revision/latest?cb=20210218001926"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Envío postal",
            "Garantia": "24 horas",
            "Resenna": "./IMG/5_Estrellas.png"
        },
        {
            "ID": 6,
            "NombreLibro": "Marvel Deluxe World War Hulk",
            "Autor": "Ignacio Echeverria",
            "Editorial": "PANINI COMICS",
            "ISBN": 9788490240663,
            "AnnoPublicacion": 2010,
            "Idioma": "Español",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 21900,
            "Descripcion": "¡El más aplastante evento de la historia de Marvel! Exiliado por un grupo de supuestos héroes al planeta de Sakaar y tras conquistar aquel mundo, Hulk regresa a la Tierra... ¡Y busca venganza contra Iron Man, Reed Richards, Doctor Extraño, Rayo Negro y todo el que se cruce en su camino! Más fuerte que nunca, y con la ayuda de una monstruosa compañía de aliados, esta vez el Goliat Verde quiere romper en dos nuestro hogar. Con guiones del genial creador de “Planeta Hulk” y dibujos del legendario John Romita Jr.",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9788490240663_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Disponible online o en tienda física",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9788490240663_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000", "https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/S/L/SLUXE071_0.jpg", "https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/S/L/SLUXE071_1.jpg" ],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Envío postal o recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "./IMG/4_5_Estrellas.png"
        },
        {
            "ID": 7,
            "NombreLibro": "Marvel Integral Civil War",
            "Autor": "Mark Millar",
            "Editorial": "PANINI COMICS",
            "ISBN": 9788490944943,
            "AnnoPublicacion": 2016,
            "Idioma": "Español",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 24800,
            "Descripcion": "Con The New Avengers Illuminati y Civil War 1-7 ¡La obra maestra que inspiró Capitán América: Civil War en un espectacular volumen integral! El Universo Marvel está cambiando. Es tiempo de elegir: ¿De qué lado estás? Un conflicto que se ha estado gestando durante años estalla al fin, rompiendo en dos a la comunidad superheroica, y enfrentando a amigo contra amigo, hermano contra hermano. Spiderman, Los Vengadores, La Patrulla-X, Los Cuatro Fantásticos... todos se verán afectados. Todos deberán elegir su lugar en la guerra. Nadie está a salvo en la saga que cambió para siempre las reglas del juego.",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9788490944943_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Disponible online o en tienda física",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9788490944943_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/S/M/SMAIN002_0.jpg","https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/S/M/SMAIN002_1.jpg"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Envío postal o recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "./IMG/4_5_Estrellas.png"
        },
        {
            "ID": 8,
            "NombreLibro": "Marvel Must Have Secret Wars",
            "Autor": "Jonathan Hickman",
            "Editorial": "PANINI COMICS",
            "ISBN": 9788411500609,
            "AnnoPublicacion": 2023,
            "Idioma": "Español",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 26800,
            "Descripcion": "¡El mayor evento de la historia de Marvel! La Incursión final tiene lugar. El Universo Marvel colisiona con el Universo Ultimate. Cuando ambos hayan desaparecido, todo lo que quedará será... Mundo de Batalla, una nueva realidad gobernada por el único hombre que pudo salvar los restos de la destrucción: Victor Von Muerte.",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9788411500609_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Disponible online",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9788411500609_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/m/smust072_0.jpg","https://www.panini.es/media/catalog/product/cache/a87cfc69c89e7921deea3a8e066ac416/s/m/smust072_3.jpg"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Envío postal",
            "Garantia": "24 horas",
            "Resenna": "./IMG/4_5_Estrellas.png"
        },
        {
            "ID": 9,
            "NombreLibro": "Caballero Luna",
            "Autor": "Bill Sienkiewicz",
            "Editorial": "PANINI COMICS",
            "ISBN": 9788411013017,
            "AnnoPublicacion": 2022,
            "Idioma": "Español",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 15900,
            "Descripcion": "En la tradición de Biblioteca Drácula, llega el primero de los nueve volúmenes quincenales que recogen la etapa completa de Doug Moench al frente del Caballero Luna. Desde el debut del Puño de Khonshu hasta las últimas miniseries desarrolladas por su más influyente guionista, pasando por su serial en el magazine de Hulk, cuya primera parte se incluye en este tomo. ¡Con la impactante llegada de Bill Sienkiewicz! Incluye secciones editoriales de los cómics originales relativas al Caballero Luna.",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9788411013017_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Disponible online o en tienda física",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9788411013017_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://www.panini.es/media/catalog/product/cache/968d306fb1cf333067a665f96384b6e4/s/b/sbclu001_2.jpg","https://www.panini.es/media/catalog/product/cache/968d306fb1cf333067a665f96384b6e4/s/b/sbclu001_3.jpg"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Envío postal o recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "./IMG/4_5_Estrellas.png"
        },
        {
            "ID": 10,
            "NombreLibro": "Pokemon Sun And Moon Vol 12",
            "Autor": "Hidenori Kusaka",
            "Editorial": "Viz Media",
            "ISBN": 9781974721764,
            "AnnoPublicacion": 2023,
            "Idioma": "Inglés",
            "Categorias": ["Ficción","Manga","Kodomo"],
            "Precio": 3900,
            "Descripcion": "¡Increíbles aventuras inspiradas en los nuevos videojuegos más vendidos Pokémon Sol y Luna ambientados en la región tropical de Alola!\nSun sueña con dinero. La luna sueña con descubrimientos científicos. Cuando sus caminos se cruzan con el Team Skull, los planes de ambos salen mal...\n¡Es la batalla final! Sol, Luna y sus amigos se enfrentan a Necrozma de una vez por todas. El destino de Ultra Megalopolis está en juego, ¡pero Necrozma se ha transformado en un Pokémon aún más poderoso!\n¿Podrá finalmente Sun volver a comprar la isla de su bisabuelo?",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9781974721764_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Solo tienda física",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9781974721764_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://www.libreriainternacional.com/media/catalog/product/9/7/9781974721764_2.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://static.wikia.nocookie.net/pokemon/images/7/77/USUM011.jpg/revision/latest?cb=20191029232342"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "./IMG/5_Estrellas.png"
        },
        {
            "ID": 11,
            "NombreLibro": "Sailor Moon Takeuchi Collection Vol 01",
            "Autor": "Naoko Takeuchi",
            "Editorial": "KODANSHA COMICS",
            "ISBN": 9781646512010,
            "AnnoPublicacion": 2022,
            "Idioma": "Inglés",
            "Categorias": ["Ficción","Manga","Shojo"],
            "Precio": 9900,
            "Descripcion": "¡Una nueva edición del manga Sailor Moon, para una nueva generación de fans! Con una traducción actualizada y un gran número de páginas en una edición portátil más asequible, perfecta para ir a donde tú o el guardián legendario de tu vida quieran llevarlo.\nLa adolescente Usagi no es la mejor atleta, nunca ha sacado buenas notas y, bueno, es un poco llorona. Pero cuando conoce a un gato que habla, comienza un viaje que le enseñará que tiene una gran fuerza justo debajo de la superficie y el corazón para inspirar y defender a sus amigas como Sailor Moon. La Sailor Moon original en una edición nueva y asequible.",
            "ImagenDestacada": "https://m.media-amazon.com/images/I/71fD6iqykdL._SY466_.jpg",
            "Stock": "Solo tienda física",
            "GaleriaImg": ["https://m.media-amazon.com/images/I/71fD6iqykdL._SY466_.jpg","https://m.media-amazon.com/images/I/713hlX3hgRL._AC_UF894,1000_QL80_.jpg","https://sailormoonfannetwork.com/wp-content/uploads/2022/03/Sailormoonmangaguide.jpg"],
            "TiempoEntrega": "4 días",
            "OpcionesEntrega": "Recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "./IMG/5_Estrellas.png"
        },
        {
            "ID": 12,
            "NombreLibro": "Solo Leveling Vol 02",
            "Autor": "Chugong",
            "Editorial": "Norma Editorial",
            "ISBN": 8467945850,
            "AnnoPublicacion": 2021,
            "Idioma": "Español",
            "Categorias": ["Ficción","Manga","Manhwa"],
            "Precio": 14800,
            "Descripcion": "¡SUNG JINWOO HA ESCAPADO DE LAS GARRAS DE LA MUERTE Y PARECE QUE HA DESPERTADO UNA NUEVA HABILIDAD!\nSung Jinwoo ha logrado salir con vida de lo que parecía una muerte segura. Tras despertarse en el hospital, una extraña pantalla que solo él puede ver aparece ante él, ¿significa eso que ha tenido un renacer? Al parecer, si cumple con las misiones que le aparecen en pantalla puede obtener puntos y recompensas para volverse más fuerte. Por otro lado, lo han reclutado para una nueva misión de rango C, pero parece que algo raro traman los del grupo… ¿Qué le ocurrirá a nuestro protagonista en esta nueva incursión?\n¡INCLUYE DOS TARJETAS DE JINWOO SOLO CON LA PRIMERA EDICIÓN!",
            "ImagenDestacada": "https://www.libreriainternacional.com/media/catalog/product/9/7/9788467945867_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000",
            "Stock": "Solo tienda física",
            "GaleriaImg": ["https://www.libreriainternacional.com/media/catalog/product/9/7/9788467945867_1.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://www.libreriainternacional.com/media/catalog/product/9/7/9788467945867_2.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000","https://www.libreriainternacional.com/media/catalog/product/9/7/9788467945867_3.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1320&width=1000"],
            "TiempoEntrega": "4 días",            
            "OpcionesEntrega": "Recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "./IMG/4_5_Estrellas.png"
        }
    ]
