const ListaProductos =
    [
        {
            "ID": 1,
            "NombreLibro": "All Star Superman Deluxe Edition",
            "Autor": "Grant Morrison",
            "Editorial": "DC COMICS",
            "ISBN": 1779513445,
            "AnnoPublicacion": 2022,
            "Idioma": "Inglés",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 28000,
            "Descripcion": "¡AVENTURAS DE SUPERMÁN! Locura al revés en el planeta Bizarro al revés.Una ciudad embotellada que demuestra que nunca podrás volver a casa.Un sol viviente empeñado en destruir a la humanidad.Un mundo sin el Hombre de Acero.Doce trabajos imposibles y meros momentos para salvar la Tierra.\nEl multipremiado ALL-STAR SUPERMAN es una historia eterna fiel al personaje más grande de la época dorada de los cómics.Sea testigo del ícono atemporal, el Hombre de Acero, en acción en esta colección de lujo llena de emoción y aclamación.",
            "ImagenDestacada": "https://m.media-amazon.com/images/I/81oiYDSaoVL._SL1500_.jpg",
            "Stock": "Disponible online",
            "GaleriaImg": ["https://m.media-amazon.com/images/I/81oiYDSaoVL._SL1500_.jpg","https://m.media-amazon.com/images/I/81UsnOXb5zL._AC_UF1000,1000_QL80_.jpg","https://i5.walmartimages.com/seo/All-Star-Superman-Paperback-9781401232054_4d5856f7-91ed-432a-a0ca-583e6ffa7e8b_1.d253c8f89f3879735cafccc1c1fa5ab6.jpeg"], 
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Envío postal",
            "Garantia": "24 horas",
            "Resenna": "./IMG/5_Estrellas.png"
        },
        {
            "ID": 2,
            "NombreLibro": "Batman The Long Halloween",
            "Autor": "Jehph Loeb",
            "Editorial": "DC Comics",
            "ISBN": 1401232590,
            "AnnoPublicacion": 2011,
            "Idioma": "Inglés",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 22800,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Disponible online o en tienda física",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Envío postal o recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 3,
            "NombreLibro": "Berserk Maximum Vol 01",
            "Autor": "Kentaro Miura",
            "Editorial": "PANINI MANGA",
            "ISBN": 9788411015035,
            "AnnoPublicacion": 2022,
            "Idioma": "Español",
            "Categorias": "LISTA",
            "Precio": 16800,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Disponible online",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Envío postal",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 4,
            "NombreLibro": "Dragon Ball Super Vol 20",
            "Autor": "Akira Toriyama",
            "Editorial": "IVREA",
            "ISBN": 1974743608,
            "AnnoPublicacion": 2023,
            "Idioma": "Español",
            "Categorias": "LISTA",
            "Precio": 7900,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Solo tienda física",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 5,
            "NombreLibro": "Jujutsu Kaisen Vol 14",
            "Autor": "Gege Akutani",
            "Editorial": "Norma Editorial",
            "ISBN": 9788411013017,
            "AnnoPublicacion": 2023,
            "Idioma": "Español",
            "Categorias": "LISTA",
            "Precio": 8900,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Disponible online",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Envío postal",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 6,
            "NombreLibro": "Marvel Deluxe World War Hulk",
            "Autor": "Ignacio Echeverria",
            "Editorial": "PANINI COMICS",
            "ISBN": 9788490240663,
            "AnnoPublicacion": 2010,
            "Idioma": "Español",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 21900,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Disponible online o en tienda física",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Envío postal o recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 7,
            "NombreLibro": "Marvel Integral Civil War",
            "Autor": "Mark Millar",
            "Editorial": "PANINI COMICS",
            "ISBN": 9788490944943,
            "AnnoPublicacion": 2016,
            "Idioma": "Español",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 24800,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Disponible online o en tienda física",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Envío postal o recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 8,
            "NombreLibro": "Marvel Must Have Secret Wars",
            "Autor": "Jonathan Hickman",
            "Editorial": "PANINI COMICS",
            "ISBN": 9788411500609,
            "AnnoPublicacion": 2023,
            "Idioma": "Español",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 26800,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Disponible online",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Envío postal",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 9,
            "NombreLibro": "Moon Knight",
            "Autor": "Bill Sienkiewicz",
            "Editorial": "PANINI COMICS",
            "ISBN": 9788411013017,
            "AnnoPublicacion": 2022,
            "Idioma": "Español",
            "Categorias": ["Ficción", "Cómics", "Americanos"],
            "Precio": 15900,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Disponible online o en tienda física",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Envío postal o recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 10,
            "NombreLibro": "Pokemon Sun And Moon Vol 12",
            "Autor": "Hidenori Kusaka",
            "Editorial": "Viz Media",
            "ISBN": 9781974721764,
            "AnnoPublicacion": 2023,
            "Idioma": "Inglés",
            "Categorias": "LISTA",
            "Precio": 3900,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Solo tienda física",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 11,
            "NombreLibro": "Sailor Moon Naoko Takeuchi Collection Vol 01",
            "Autor": "Naoko Takeuchi",
            "Editorial": "KODANSHA COMICS",
            "ISBN": 9781646512010,
            "AnnoPublicacion": 2022,
            "Idioma": "Inglés",
            "Categorias": "LISTA",
            "Precio": 9900,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Solo tienda física",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        },
        {
            "ID": 12,
            "NombreLibro": "Solo Leveling Vol 02",
            "Autor": "Chugong",
            "Editorial": "NORMA EDITORIAL",
            "ISBN": 8467945850,
            "AnnoPublicacion": 2021,
            "Idioma": "Español",
            "Categorias": "LISTA",
            "Precio": 14800,
            "Descripcion": "AQUI DESCRIP",
            "ImagenDestacada": "IMAGENES DEST",
            "Stock": "Solo tienda física",
            "GaleriaImg": "LISTA",
            "TiempoEntrega": "4 días",
            "GastosEnvio": "Dentro de GAM: 2500. Fuera de GAM: 5620",
            "OpcionesEntrega": "Recogido en tienda",
            "Garantia": "24 horas",
            "Resenna": "RESENNA"
        }
    ]
